version: 2.1  # the version of the config circleci file

references:

  working_directory: &working_directory ~/workspace

  container_config: &container_config
    working_directory: *working_directory
    docker:
      - image: cimg/openjdk:11.0.8

  check_version: &check_version
    run:
      name: Check Java *check_version
      command: java -version
  
  restore_cache: &restore_cache
    restore_cache:  
      name: Restore Cache
      key: dependencies-{{ checksum "pom.xml" }}'  
  
  install_maven: &install_maven
    run:
      name: Install maven
      command: mvn clean install    

  install_dependencies: &install_dependencies
    run:
      name: Install dependencies
      command: mvn dependency:go-offline 

  save_cache: &save_cache
    save_cache:  
      name: Save Cache
      key: dependencies-{{ checksum "pom.xml" }}'  
      paths:
        - ~/.m2 

  save_working_directory: &save_working_directory
    persist_to_workspace:
      root: *working_directory
      paths:
        - .

  mount_workspace: &mount_workspace
    attach_workspace:
      at: *working_directory

  validate: &validate
    run:
      name: Validate 
      command: mvn -B validate  
  
  compile: &compile
    run:
      name: Compile 
      command:  mvn -B compile  

  run_test: &run_test
    run:
      name: Test 
      command:  mvn -B test  
  
  store_test_results: &store_test_results
    store_test_results:
      path: /target/test-results

  refactor_only: &refactor_only
    filters:
      branches:
        only:
          - refactor		

  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: true

  docker_login_gcp: &docker_login_gcp
    run:
      name: Docker Login GCP
      command: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

  publish_images_local: &publish_images_local
    run:
      name: Publish Images Local
      command: |
        docker build -f Dockerfile -t limarktest/gradle-docker-app:latest .  

  publish_images_gcp: &publish_images_gcp
    run:
      name: Publish Images GCP
      command: |
        docker push limarktest/gradle-docker-app:latest

  set_git_hash: &set_git_hash
    run:
      name: Set Git Hash
      command: |
        echo "export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)" >> $BASH_ENV
        source $BASH_ENV

executors:

  default:
    <<: *container_config
    resource_class: medium+                                                   		

jobs:

  compile:
    <<: *container_config
    resource_class: medium+
    parallelism: 8
    steps:
      - checkout
      - *check_version
      - *restore_cache
      - *install_maven
      - *install_dependencies
      - *save_cache
      - *save_working_directory

  test:
    <<: *container_config
    resource_class: medium+
    parallelism: 8
    steps:
      - *mount_workspace
      - *restore_cache
      - *install_maven
      - *install_dependencies
      - *validate
      - *compile
      - *run_test 
      - *store_test_results
      - *save_working_directory  

  build_and_publish_gcp:
    <<: *container_config
    resource_class: medium+
    parallelism: 8
    steps:
      - *mount_workspace
      - *restore_cache
      - *install_maven
      - *install_dependencies
      - *setup_remote_docker
      - *set_git_hash
      - *publish_images_local
      - *docker_login_gcp
      - *publish_images_gcp
      - *save_working_directory
  
workflows:
  build:
    jobs:
      - compile:
          <<: *refactor_only
      - test:
          <<: *refactor_only
          requires:
            - compile
      - build_and_publish_gcp:
          <<: *refactor_only
          requires:
            - compile