version: 2.1  # the version of the config circleci file
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: 'dependencies-{{ checksum "pom.xml" }}'
      - run:
          name: Install
          command: mvn clean install
      - run:
          name: Install dependencies
          command: mvn dependency:go-offline
      - save_cache:
          key: 'dependencies-{{ checksum "pom.xml" }}'
          paths:
            - ~/.m2
      - run:
          name: Validate
          command: mvn -B validate
      - run:
          name: Compile
          command: mvn -B compile
      - run:
          name: Test
          command: mvn -B test