version: 2.1  # the version of the config circleci file

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.8
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Check java version
          command: java -version
      - restore_cache:
          key: 'dependencies-{{ checksum "pom.xml" }}'
      - run:
          name: Install
          command: mvn clean install
      - run:
          name: Install dependencies
          command: mvn dependency:go-offline
      - save_cache:
          key: 'dependencies-{{ checksum "pom.xml" }}'
          paths:
            - ~/.m2
      - run:
          name: Validate
          command: mvn -B validate
      - run:
          name: Compile
          command: mvn -B compile
      - run:
          name: Test
          command: mvn -B test
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Deploy Image
          command: echo "Deploy"
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master