version: 2.1  # the version of the config circleci file

references:

  working_directory: &working_directory ~/workspace

  container_config: &container_config
    working_directory: *working_directory
    docker:
      - image: cimg/openjdk:11.0.8

  check_version: &check_version
    run:
      name: Check Java *check_version
      command: java -version
  
  restore_cache: &restore_cache
    restore_cache:  
      name: Restore Cache
      key: dependencies-{{ checksum "pom.xml" }}'  
  
  install: &install
    run:
      name: Install 
      command: mvn clean install    

  install_dependencies: &install_dependencies
    run:
      name: Install 
      command: mvn dependency:go-offline 

  save_cache: &save_cache
    save_cache:  
      name: Save Cache
      key: dependencies-{{ checksum "pom.xml" }}'  
      paths:
        - ~/.m2 

  validate: &validate
    run:
      name: Validate 
      command: mvn -B validate  
  
  compile: &compile
    run:
      name: Compile 
      command:  mvn -B compile  

  test: &test
    run:
      name: Test 
      command:  mvn -B test  

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *check_version
      - *restore_cache
      - *install
      - *install_dependencies
      - *save_cache
      - *validate
      - *compile
      - *test
  deploy:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Deploy Image
          command: echo "Deploy"
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: refactor
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: refactor