version: 2.1  # the version of the config circleci file

references:

  working_directory: &working_directory ~/workspace

  container_config: &container_config
    working_directory: *working_directory
    docker:
      - image: cimg/openjdk:11.0.8

  check_version: &check_version
    run:
      name: Check Java *check_version
      command: java -version
  
  restore_cache: &restore_cache
    restore_cache:  
      name: Restore Cache
      key: dependencies-{{ checksum "pom.xml" }}'  
  
  install: &install
    run:
      name: Install 
      command: mvn clean install    

  install_dependencies: &install_dependencies
    run:
      name: Install 
      command: mvn dependency:go-offline 

  save_cache: &save_cache
    save_cache:  
      name: Save Cache
      key: dependencies-{{ checksum "pom.xml" }}'  
      paths:
        - ~/.m2 

  save_working_directory: &save_working_directory
    persist_to_workspace:
      root: *working_directory
      paths:
        - .

  mount_workspace: &mount_workspace
    attach_workspace:
      at: *working_directory

  validate: &validate
    run:
      name: Validate 
      command: mvn -B validate  
  
  compile: &compile
    run:
      name: Compile 
      command:  mvn -B compile  

  run_test: &run_test
    run:
      name: Test 
      command:  mvn -B test  
  
  store_test_results: &store_test_results
    store_test_results:
      path: /target/test-results

  refactor_only: &refactor_only
    filters:
      branches:
        only:
          - refactor		

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - *check_version
      - *restore_cache
      - *install
      - *install_dependencies
      - *save_cache
      - *save_working_directory

  test:
    <<: *container_config
    steps:
      - *mount_workspace
      - *restore_cache
      - *install
      - *install_dependencies
      - *validate
      - *compile
      - *run_test 
      - *store_test_results
      - *save_working_directory  
  
workflows:
  build:
    jobs:
      - build:
          <<: *refactor_only
      - deploy:
          <<: *refactor_only
          requires:
            - build